site_name: kTemplate

repo_url: https://github.com/hoishing/kTemplate
extra_css:
  - stylesheets/extra.css

theme:
  font:
    text: Varela Round
  name: "material"
  icon:
    repo: fontawesome/brands/github
  favicon: https://api.iconify.design/heroicons-solid/template.svg?color=white
  logo: https://api.iconify.design/heroicons-solid/template.svg?color=white
  palette:
    # Palette toggle for dark mode
    - primary: deep purple
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

    # Palette toggle for light mode
    - primary: deep purple
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

  features:
    - navigation.instant
    - navigation.tracking
    # - navigation.sections
    - navigation.expand
    # - toc.integrate

plugins:
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_signature_annotations: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets

nav:
  - Quick Start: index.md
  - Usage: usage.md
  - References: reference.md
  - License: license.md
  - Author: https://hoishing.github.io
